name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Copy Texures to replacements
        shell: cmd
        run: VCSCopyTextures.exe

      - name: Unscale Textures
        shell: cmd
        run: unscale.bat

      - name: Pack Textures
        uses: ThirteenAG/zip-release@master
        with:
          path: './replacements'
          type: 'zip'
          filename: ${{ github.event.repository.name }}.zip
      - name: Get release info
        id: release_info
        uses: cardinalby/git-get-release-action@1.1.1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: latest
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ steps.release_info.outputs.name }}
          body: ${{ steps.release_info.outputs.body }}
          tag: ${{ steps.release_info.outputs.tag_name }}
          artifacts: "*.zip"